### ISSUE TITLE
Support conversion between Box<[u8]>/`Box<[f32]>` (and similarly for Vec)

### ISSUE THREAD

**Issue by Manishearth** [sdroege/byte-slice-cast#1]
Would be useful for servo-media  so that we can avoid copies at the sink.

**Comment by sdroege** [comment]
Sounds like a very good idea. I believe all this could simply be implemented for `AsRef<[T]>` and `AsMut<[T]>` to cover these two variants (slices and boxed slices), and many other things (e.g. `Vec`)

I'll look into this in the next days unless you want to prepare a PR

**Comment by sdroege** [comment]
Needs solving some trait puzzles, but I have a half-finished version now. More later

**Comment by sdroege** [comment]
Please check if this works well for you and let me know, I'll do a new release then :)

**Comment by sdroege** [comment]
The commit changes the API behaviour slightly. While code still typechecks, the borrow checker is not so happy anymore and requires using more intermediate variables, e.g. this in GStreamer:

```diff
--- a/examples/src/bin/appsink.rs
+++ b/examples/src/bin/appsink.rs
@@ -93,7 +93,8 @@ fn create_pipeline() -> Result<gst::Pipeline, Error> {
                     return gst::FlowReturn::Error;
                 };
 
-                let samples = if let Ok(samples) = map.as_slice().as_slice_of::<i16>() {
+                let slice = map.as_slice();
+                let samples = if let Ok(samples) = slice.as_slice_of::<i16>() {
                     samples
                 } else {
                     gst_element_error!(
```

I'm not entirely sure why yet and if this can be fixed :)

**Comment by sdroege** [comment]
The problem basically boils down to

```rust
fn foo<T: AsRef<[u8]>>(slice: &T) -> &[u8] {
    slice.as_ref()
}

fn bar(slice: &[u8]) -> &[u8] {
    slice
}

fn main() {
    let slice = [1, 2, 3, 4];

    // This fails and the & before the inner foo is necessary
    // 13 |     let s = foo(&foo(&slice));
    //    |                  ^^^^^^^^^^^ - temporary value dropped here while still borrowed
    //    |                  |
    //    |                  temporary value does not live long enough

    let s = foo(&foo(&slice));
    println!("{:?}", s);

    // Without the & it fails differently and I'm not sure why:
    // &[u8] is Sized and that's what it operates on, not [u8]. The return value is &[u8]
    // 13 |     let s = foo(foo(&slice));
    //    |             ^^^ `[u8]` does not have a constant size known at compile-time
    //    |
    //    = help: the trait `std::marker::Sized` is not implemented for `[u8]`

    let s = foo(foo(&slice));
    println!("{:?}", s);

    // This works with and without &
    let b = bar(bar(&slice));
    println!("{:?}", b);
}
```

Do you have an explanation why `AsRef` changes how borrowing works here, and also why the additional ampersand is needed?

**Comment by Manishearth** [comment]
Well, you can't move `[u8]`, you can only move `Box<[u8]>`. `[u8]` is an unsized type so you can't interact with it other than behind a pointer.

**Comment by sdroege** [comment]
But everything is using references, not the actual values. I would expect the generic version above to be equivalent with the concrete one, which it is when simply replacing the types

**Comment by Manishearth** [comment]
Oh, huh. Yeah, that's weird. File a rustc issue?

``rust
fn foo<T: AsRef<[u8]>>(slice: &T) -> &[u8] {
    slice.as_ref()
}

let y = foo(&slice);
```

should compile

**Comment by sdroege** [comment]
Thanks, will do later. I wasn't sure if I just missed something silly :)

**Comment by sdroege** [comment]
In any case, the current code in GIT should work fine for your use case... you might just have to introduce some more variable bindings :)

**Comment by sdroege** [comment]
d4f370b890c3a6f95f85b65c83d983e830af91fe seems to solve this. I'll do a 0.2 release then, all my existing code using the crate is still compiling fine now.

**Comment by sdroege** [comment]
This commit might also be relevant for you https://github.com/sdroege/gstreamer-rs/commit/8d0a0ee6b15c2ceb821a65bbc08f06d7068bcb5e
