### ISSUE TITLE
Cannot compile on wasm32-unknown-emscripten target (debug mode)

### ISSUE THREAD

**Issue by georgeroman** [sdroege/byte-slice-cast#13]
I'm trying to compile a project that depends on `byte-slice-cast` to a `wasm32-unknown-emscripten` target. However, when building in debug mode, I get the following weird error:
```
Compiling byte-slice-cast v0.3.5
Referencing function in another module!
  call void <badref>(i8* %22), !dbg !149
; ModuleID = 'byte_slice_cast.v1okijvo-cgu.15'
void (i8*)* <badref>
; ModuleID = '
error: could not compile `byte-slice-cast`.
```

Building in release mode works just fine. Compiling any project that depends on `byte-slice-cast` (even a simple hello world project that does nothing but has a dependency on it) to that specific target results in this error. Any ideas on why this is happening?

**Comment by sdroege** [comment]
Not sure, this looks like a bug in the compiler to me?

**Comment by sdroege** [comment]
I.e. can you report it there and link the issue here? Thanks :)

**Comment by sdroege** [comment]
Let's close this here for now
