### ISSUE TITLE
What's keeping this from being 1.0 right now?

### ISSUE THREAD

**Issue by Lokathor** [sdroege/byte-slice-cast#2]
This API is the _exact_ API that I was imagining when I went to look for a crate like this. More generic even, which is cool.

The version is only at 0.2, but it's been sitting there for half a year it looks like. Is there something holding it back from being 1.0 or could it be version bumped?

**Comment by sdroege** [comment]
Nothing is really preventing this from being 1.0 apart from some wider usage to see if there are any deficiencies with the current API.

In what context are you using it? :)

**Comment by Lokathor** [comment]
I know a guy who uses it on switch to write driver type code. File system parsing sort of stuff.

**Comment by sdroege** [comment]
>     1. it's a moral difference, I'll admit. It shows a confidence that the package can be used for serious purposes without creeping dangers.

I never really got this obsession with numbers people seem to have. There's enough crap out there that is versioned 1.0 or even higher, and enough great stuff that has lower version numbers. In the end you always have to look at the dependency yourself, everybody has a different understand of what "1.0-quality" means.

When I do the next update I'll update the version to 1.0.

>     2\. no one would have to update anything if they didn't want to. The current version doesn't go away even if a 1.0 version comes out.

And then you potentially have multiple versions in your dependency tree, which seems more ugly than cosmetics about version numbers.

**Comment by sdroege** [comment]
https://github.com/sdroege/byte-slice-cast/pull/3 and https://github.com/sdroege/byte-slice-cast/pull/4 implemented some API changes since last time this issue got comments.

If there's no new API change coming up in the next 2-3 months, I'll consider releasing the current API as 1.0.

**Comment by dignifiedquire** [comment]
Just found this crate, does exactly what I needed, API matched very well the usages 👍 thank you

**Comment by sdroege** [comment]
Currently my main worry is that the `Vec` transformation is actually unsound: it causes memory to be freed with a different alignment requirement than it was allocated with, which I think is not allowed. I'm not aware of any allocator breaking from this but that might of course change in the future.

**Comment by Lokathor** [comment]
Ah, I didn't notice the Vec cast (or maybe it wasn't there 1.5 years ago).

Yeah that is unsound.

**Comment by sdroege** [comment]
I guess let's get rid of it then and release everything else as 1.0. Too bad, it's quite useful.

**Comment by Lokathor** [comment]
Bytemuck has a vec cast that checks alignment, which is sound.

**Comment by sdroege** [comment]
This here also checks alignment, that's not the problem. The problem is [this](https://doc.rust-lang.org/alloc/alloc/trait.AllocRef.html#memory-fitting), coming from [`AllocRef::dealloc()`](https://doc.rust-lang.org/alloc/alloc/trait.AllocRef.html#tymethod.dealloc):

> Deallocates the memory referenced by ptr.
> Safety
>
>    * ptr must denote a block of memory currently allocated via this allocator, and
>    * **layout must fit that block of memory.**

> Memory fitting
> [...]
> The block must be allocated with the **same** alignment as layout.align(), and

This means that you can't drop a `Vec<u16>` safely as a `Vec<u8>`. While the alignment is **compatible** in this direction, it is not the **same**.

**Comment by Lokathor** [comment]
yeah just make the alignment check only allow equal alignment ;P

**Comment by sdroege** [comment]
That seems not very useful :) Sure, you can go from `u32` to `f32` and `u64` to `f64` and back but otherwise...?

**Comment by sdroege** [comment]
See https://github.com/sdroege/byte-slice-cast/pull/15
