### ISSUE TITLE
Please add support for manually selecting endianness

### ISSUE THREAD

**Issue by ohmyarch** [sdroege/byte-slice-cast#21]
For example: https://docs.rs/byteorder/latest/byteorder/index.html#types

**Comment by sdroege** [comment]
That doesn't work the way this is implemented. The data always must be in native endianness as it's directly accessed without any conversion in between to provide the lowest possible overhead, and to compile down to efficient assembly.
Similarly the data must have the correct alignment etc for the very same reasons.

If conversions/etc are needed then you can just create e.g. iterator adapters or some other translation API that e.g. makes use of the `byteorder` crate or the `core` API for converting bytes of arbitrary endianness to native endianness integers/floats.

----

What exactly is your use-case here?

**Comment by ohmyarch** [comment]
👌
