### ISSUE TITLE
Unsound usages of unsafe implementation from `T` to `[u8]`

### ISSUE THREAD

**Issue by llooFlashooll** [sdroege/byte-slice-cast#22]
Hi, I am scanning the byte-slice-cast in the latest version with my own static analyzer tool.

Unsafe conversion found at: src/lib.rs:237:43: 237:70.
``` rust
fn to_byte_slice<T: AsRef<[$to]> + ?Sized>(slice: &T) -> &[u8] {
    let slice = slice.as_ref();
    let len = slice.len() * mem::size_of::<$to>();
    unsafe {
        slice::from_raw_parts(slice.as_ptr() as *const u8, len)
    }
}
```

Unsafe conversion found at: src/lib.rs:248:47: 248:76.
``` rust
fn to_mut_byte_slice<T: AsMut<[$to]> + ?Sized>(slice: &mut T) -> &mut [u8] {
    let slice = slice.as_mut();
    let len = slice.len() * mem::size_of::<$to>();
    unsafe {
        slice::from_raw_parts_mut(slice.as_mut_ptr() as *mut u8, len)
    }
}
```

Unsafe conversion found at: src/lib.rs:303:43: 303:70.
``` rust
fn to_byte_slice<T: AsRef<[[$to; N]]> + ?Sized>(slice: &T) -> &[u8] {
    let slice = slice.as_ref();
    let len = slice.len() * mem::size_of::<[$to; N]>();
    unsafe {
        slice::from_raw_parts(slice.as_ptr() as *const u8, len)
    }
}
```

Unsafe conversion found at: src/lib.rs:314:47: 314:76.
``` rust
fn to_mut_byte_slice<T: AsMut<[[$to; N]]> + ?Sized>(slice: &mut T) -> &mut [u8] {
    let slice = slice.as_mut();
    let len = slice.len() * mem::size_of::<[$to; N]>();
    unsafe {
        slice::from_raw_parts_mut(slice.as_mut_ptr() as *mut u8, len)
    }
}
```

This unsound implementation would create a misalignment issues. The `T` and `[u8]` are different types.

This would potentially cause [undefined behaviors](https://doc.rust-lang.org/reference/behavior-considered-undefined.html) in Rust. If we further manipulate the problematic converted types, it would potentially lead to different consequences. I am reporting this issue for your attention.

**Comment by sdroege** [comment]
Why do you think this would cause alignment mismatches? `u8` has the minimum possible alignment requirement (byte alignment), and it's only implemented for types `$to` where every byte is valid to access.

I think there's a bug in your static analyzer.

**Comment by sdroege** [comment]
I'm curious why you thought this is unsound though

**Comment by sdroege** [comment]
No worries
